// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contractID.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
//const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContractID struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	LanguageType         string   `protobuf:"bytes,4,opt,name=language_type,json=languageType,proto3" json:"language_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractID) Reset()         { *m = ContractID{} }
func (m *ContractID) String() string { return proto.CompactTextString(m) }
func (*ContractID) ProtoMessage()    {}
func (*ContractID) Descriptor() ([]byte, []int) {
	return fileDescriptor_6caf8a299410f13b, []int{0}
}

func (m *ContractID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractID.Unmarshal(m, b)
}
func (m *ContractID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractID.Marshal(b, m, deterministic)
}
func (m *ContractID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractID.Merge(m, src)
}
func (m *ContractID) XXX_Size() int {
	return xxx_messageInfo_ContractID.Size(m)
}
func (m *ContractID) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractID.DiscardUnknown(m)
}

var xxx_messageInfo_ContractID proto.InternalMessageInfo

func (m *ContractID) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContractID) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ContractID) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ContractID) GetLanguageType() string {
	if m != nil {
		return m.LanguageType
	}
	return ""
}

func init() {
	proto.RegisterType((*ContractID)(nil), "api.ContractID")
}

func init() { proto.RegisterFile("contractID.proto", fileDescriptor_6caf8a299410f13b) }

var fileDescriptor_6caf8a299410f13b = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xce, 0xcf, 0x2b,
	0x29, 0x4a, 0x4c, 0x2e, 0xf1, 0x74, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c,
	0xc8, 0x54, 0x2a, 0xe6, 0xe2, 0x72, 0x86, 0x4b, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6,
	0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x12, 0x5c, 0xec, 0x65, 0xa9, 0x45,
	0xc5, 0x99, 0xf9, 0x79, 0x12, 0x4c, 0x60, 0x61, 0x18, 0x17, 0xa4, 0xba, 0xa4, 0xb2, 0x20, 0x55,
	0x82, 0x19, 0xa2, 0x1a, 0xc4, 0x16, 0x52, 0xe6, 0xe2, 0xcd, 0x49, 0xcc, 0x4b, 0x2f, 0x4d, 0x4c,
	0x4f, 0x8d, 0x07, 0x4b, 0xb2, 0x80, 0x25, 0x79, 0x60, 0x82, 0x21, 0x95, 0x05, 0xa9, 0x49, 0x6c,
	0x60, 0x07, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x41, 0x94, 0x56, 0x89, 0x94, 0x00, 0x00,
	0x00,
}
