// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contract_peer.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
//const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContractPeerRequest struct {
	ContractId           *ContractID `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Method               string      `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Key                  string      `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Payload              string      `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Sign                 string      `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	AppId                string      `protobuf:"bytes,6,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ChannelName          string      `protobuf:"bytes,7,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ContractPeerRequest) Reset()         { *m = ContractPeerRequest{} }
func (m *ContractPeerRequest) String() string { return proto.CompactTextString(m) }
func (*ContractPeerRequest) ProtoMessage()    {}
func (*ContractPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38da68d5df68e4a2, []int{0}
}

func (m *ContractPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractPeerRequest.Unmarshal(m, b)
}
func (m *ContractPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractPeerRequest.Marshal(b, m, deterministic)
}
func (m *ContractPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractPeerRequest.Merge(m, src)
}
func (m *ContractPeerRequest) XXX_Size() int {
	return xxx_messageInfo_ContractPeerRequest.Size(m)
}
func (m *ContractPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContractPeerRequest proto.InternalMessageInfo

func (m *ContractPeerRequest) GetContractId() *ContractID {
	if m != nil {
		return m.ContractId
	}
	return nil
}

func (m *ContractPeerRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *ContractPeerRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ContractPeerRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *ContractPeerRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *ContractPeerRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ContractPeerRequest) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

type InvokeContractRequest struct {
	ContractId           *ContractID   `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Method               string        `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload              string        `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ChannelName          string        `protobuf:"bytes,4,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	AppId                string        `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Caller               []*ContractID `protobuf:"bytes,6,rep,name=caller,proto3" json:"caller,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InvokeContractRequest) Reset()         { *m = InvokeContractRequest{} }
func (m *InvokeContractRequest) String() string { return proto.CompactTextString(m) }
func (*InvokeContractRequest) ProtoMessage()    {}
func (*InvokeContractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38da68d5df68e4a2, []int{1}
}

func (m *InvokeContractRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeContractRequest.Unmarshal(m, b)
}
func (m *InvokeContractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeContractRequest.Marshal(b, m, deterministic)
}
func (m *InvokeContractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeContractRequest.Merge(m, src)
}
func (m *InvokeContractRequest) XXX_Size() int {
	return xxx_messageInfo_InvokeContractRequest.Size(m)
}
func (m *InvokeContractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeContractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeContractRequest proto.InternalMessageInfo

func (m *InvokeContractRequest) GetContractId() *ContractID {
	if m != nil {
		return m.ContractId
	}
	return nil
}

func (m *InvokeContractRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *InvokeContractRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *InvokeContractRequest) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *InvokeContractRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *InvokeContractRequest) GetCaller() []*ContractID {
	if m != nil {
		return m.Caller
	}
	return nil
}

func init() {
	proto.RegisterType((*ContractPeerRequest)(nil), "api.ContractPeerRequest")
	proto.RegisterType((*InvokeContractRequest)(nil), "api.InvokeContractRequest")
}

func init() { proto.RegisterFile("contract_peer.proto", fileDescriptor_38da68d5df68e4a2) }

var fileDescriptor_38da68d5df68e4a2 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xcd, 0x4e, 0x02, 0x31,
	0x10, 0x76, 0x5d, 0x58, 0x74, 0xf0, 0x87, 0x0c, 0xc1, 0x34, 0x7b, 0x42, 0x2e, 0x72, 0x22, 0x06,
	0xe3, 0xd1, 0x13, 0x5e, 0xb8, 0x18, 0xb3, 0x3c, 0x00, 0xa9, 0xdd, 0x09, 0x34, 0xec, 0xb6, 0xb5,
	0x54, 0x12, 0x9e, 0xc1, 0x27, 0xf4, 0xe2, 0xb3, 0x18, 0xca, 0x42, 0x76, 0x81, 0xa3, 0xb7, 0x99,
	0xef, 0x9b, 0x99, 0x7e, 0xdf, 0x4c, 0xa1, 0x2d, 0xb4, 0x72, 0x96, 0x0b, 0x37, 0x35, 0x44, 0x76,
	0x60, 0xac, 0x76, 0x1a, 0x43, 0x6e, 0x64, 0xdc, 0xda, 0x31, 0xe3, 0xd7, 0x2d, 0x1c, 0xb7, 0xac,
	0x11, 0x53, 0xa1, 0xf3, 0x5c, 0xab, 0x2d, 0xd2, 0xfb, 0x09, 0xa0, 0x3d, 0x2a, 0xca, 0xde, 0x89,
	0x6c, 0x42, 0x9f, 0x5f, 0xb4, 0x74, 0xf8, 0x08, 0xcd, 0xfd, 0x5c, 0x99, 0xb2, 0xa0, 0x1b, 0xf4,
	0x9b, 0xc3, 0xdb, 0x01, 0x37, 0x72, 0x30, 0xda, 0x4f, 0x4d, 0x60, 0xff, 0x42, 0x8a, 0x77, 0x10,
	0xe5, 0xe4, 0xe6, 0x3a, 0x65, 0xe7, 0xdd, 0xa0, 0x7f, 0x99, 0x14, 0x19, 0xb6, 0x20, 0x5c, 0xd0,
	0x9a, 0x85, 0x1e, 0xdc, 0x84, 0xc8, 0xa0, 0x61, 0xf8, 0x3a, 0xd3, 0x3c, 0x65, 0x35, 0x8f, 0xee,
	0x52, 0x44, 0xa8, 0x2d, 0xe5, 0x4c, 0xb1, 0xba, 0x87, 0x7d, 0x8c, 0x1d, 0x88, 0xb8, 0x31, 0x1b,
	0x11, 0x91, 0x47, 0xeb, 0xdc, 0x98, 0x71, 0x8a, 0xf7, 0x70, 0x25, 0xe6, 0x5c, 0x29, 0xca, 0xa6,
	0x8a, 0xe7, 0xc4, 0x1a, 0x9e, 0x6c, 0x16, 0xd8, 0x1b, 0xcf, 0xa9, 0xf7, 0x1b, 0x40, 0x67, 0xac,
	0x56, 0x7a, 0x41, 0x3b, 0xc9, 0xff, 0xef, 0xae, 0xe4, 0x25, 0xac, 0x7a, 0x39, 0x14, 0x58, 0x3b,
	0x12, 0x58, 0xb2, 0x56, 0x2f, 0x5b, 0x7b, 0x80, 0x48, 0xf0, 0x2c, 0x23, 0xcb, 0xa2, 0x6e, 0x78,
	0x4a, 0x58, 0x41, 0x0f, 0xbf, 0x0f, 0x8e, 0x37, 0x21, 0xbb, 0x92, 0x82, 0xf0, 0x19, 0x2e, 0x66,
	0xe4, 0x26, 0x8e, 0x3b, 0x42, 0x56, 0x69, 0x2e, 0x9d, 0x38, 0xbe, 0xf6, 0x4c, 0x62, 0x44, 0x42,
	0x26, 0x5b, 0xf7, 0xce, 0xf0, 0x05, 0x6e, 0x64, 0x65, 0x5d, 0x18, 0xfb, 0x92, 0x93, 0x3b, 0x3c,
	0x6a, 0xff, 0x88, 0xfc, 0x8f, 0x7a, 0xfa, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xa3, 0x7c, 0x9b,
	0x91, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContractPeerServiceClient is the client API for ContractPeerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContractPeerServiceClient interface {
	GetState(ctx context.Context, in *ContractPeerRequest, opts ...grpc.CallOption) (*RpcReply, error)
	InvokeContract(ctx context.Context, in *InvokeContractRequest, opts ...grpc.CallOption) (*RpcReply, error)
}

type contractPeerServiceClient struct {
	cc *grpc.ClientConn
}

func NewContractPeerServiceClient(cc *grpc.ClientConn) ContractPeerServiceClient {
	return &contractPeerServiceClient{cc}
}

func (c *contractPeerServiceClient) GetState(ctx context.Context, in *ContractPeerRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, "/api.ContractPeerService/getState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractPeerServiceClient) InvokeContract(ctx context.Context, in *InvokeContractRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, "/api.ContractPeerService/invokeContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractPeerServiceServer is the server API for ContractPeerService service.
type ContractPeerServiceServer interface {
	GetState(context.Context, *ContractPeerRequest) (*RpcReply, error)
	InvokeContract(context.Context, *InvokeContractRequest) (*RpcReply, error)
}

// UnimplementedContractPeerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedContractPeerServiceServer struct {
}

func (*UnimplementedContractPeerServiceServer) GetState(ctx context.Context, req *ContractPeerRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (*UnimplementedContractPeerServiceServer) InvokeContract(ctx context.Context, req *InvokeContractRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeContract not implemented")
}

func RegisterContractPeerServiceServer(s *grpc.Server, srv ContractPeerServiceServer) {
	s.RegisterService(&_ContractPeerService_serviceDesc, srv)
}

func _ContractPeerService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContractPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractPeerServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ContractPeerService/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractPeerServiceServer).GetState(ctx, req.(*ContractPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractPeerService_InvokeContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractPeerServiceServer).InvokeContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ContractPeerService/InvokeContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractPeerServiceServer).InvokeContract(ctx, req.(*InvokeContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContractPeerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ContractPeerService",
	HandlerType: (*ContractPeerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getState",
			Handler:    _ContractPeerService_GetState_Handler,
		},
		{
			MethodName: "invokeContract",
			Handler:    _ContractPeerService_InvokeContract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contract_peer.proto",
}
