// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sdk_peer.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
//const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SdkPeerRequest struct {
	ContractId           *ContractID `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Method               string      `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload              string      `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ChannelName          string      `protobuf:"bytes,4,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	AppId                string      `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Sign                 string      `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
	File                 []byte      `protobuf:"bytes,7,opt,name=file,proto3" json:"file,omitempty"`
	UserSign             string      `protobuf:"bytes,8,opt,name=user_sign,json=userSign,proto3" json:"user_sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SdkPeerRequest) Reset()         { *m = SdkPeerRequest{} }
func (m *SdkPeerRequest) String() string { return proto.CompactTextString(m) }
func (*SdkPeerRequest) ProtoMessage()    {}
func (*SdkPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca05cd00fb21c1e, []int{0}
}

func (m *SdkPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkPeerRequest.Unmarshal(m, b)
}
func (m *SdkPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkPeerRequest.Marshal(b, m, deterministic)
}
func (m *SdkPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkPeerRequest.Merge(m, src)
}
func (m *SdkPeerRequest) XXX_Size() int {
	return xxx_messageInfo_SdkPeerRequest.Size(m)
}
func (m *SdkPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SdkPeerRequest proto.InternalMessageInfo

func (m *SdkPeerRequest) GetContractId() *ContractID {
	if m != nil {
		return m.ContractId
	}
	return nil
}

func (m *SdkPeerRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *SdkPeerRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *SdkPeerRequest) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *SdkPeerRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SdkPeerRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *SdkPeerRequest) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *SdkPeerRequest) GetUserSign() string {
	if m != nil {
		return m.UserSign
	}
	return ""
}

type ContractSpec struct {
	ContractId           *ContractID `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	ContractInput        string      `protobuf:"bytes,2,opt,name=contract_input,json=contractInput,proto3" json:"contract_input,omitempty"`
	FileName             string      `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ChannelName          string      `protobuf:"bytes,4,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	AppId                string      `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Sign                 string      `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ContractSpec) Reset()         { *m = ContractSpec{} }
func (m *ContractSpec) String() string { return proto.CompactTextString(m) }
func (*ContractSpec) ProtoMessage()    {}
func (*ContractSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca05cd00fb21c1e, []int{1}
}

func (m *ContractSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractSpec.Unmarshal(m, b)
}
func (m *ContractSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractSpec.Marshal(b, m, deterministic)
}
func (m *ContractSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractSpec.Merge(m, src)
}
func (m *ContractSpec) XXX_Size() int {
	return xxx_messageInfo_ContractSpec.Size(m)
}
func (m *ContractSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ContractSpec proto.InternalMessageInfo

func (m *ContractSpec) GetContractId() *ContractID {
	if m != nil {
		return m.ContractId
	}
	return nil
}

func (m *ContractSpec) GetContractInput() string {
	if m != nil {
		return m.ContractInput
	}
	return ""
}

func (m *ContractSpec) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *ContractSpec) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *ContractSpec) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ContractSpec) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func init() {
	proto.RegisterType((*SdkPeerRequest)(nil), "api.SdkPeerRequest")
	proto.RegisterType((*ContractSpec)(nil), "api.ContractSpec")
}

func init() { proto.RegisterFile("sdk_peer.proto", fileDescriptor_cca05cd00fb21c1e) }

var fileDescriptor_cca05cd00fb21c1e = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x41, 0xae, 0xd3, 0x30,
	0x10, 0x86, 0xc9, 0x7b, 0x6d, 0x9a, 0x4e, 0xd3, 0x50, 0x8c, 0x40, 0x51, 0xd9, 0x94, 0x4a, 0x48,
	0xdd, 0x10, 0x55, 0x05, 0x71, 0x81, 0xb2, 0xe9, 0x06, 0xa1, 0xe4, 0x00, 0x91, 0x71, 0x86, 0xd6,
	0x6a, 0x62, 0xbb, 0x8e, 0x53, 0xa9, 0xe7, 0xe3, 0x06, 0x5c, 0x85, 0x0b, 0x20, 0x3b, 0x4d, 0x50,
	0xc5, 0xa6, 0xa0, 0xb7, 0xb3, 0xbf, 0xf9, 0xff, 0xd1, 0xfc, 0x93, 0x18, 0xa2, 0xba, 0x38, 0xe6,
	0x0a, 0x51, 0x27, 0x4a, 0x4b, 0x23, 0xc9, 0x23, 0x55, 0x7c, 0x3e, 0x63, 0x52, 0x18, 0x4d, 0x99,
	0xd9, 0x7d, 0x6e, 0xf1, 0x7c, 0xa6, 0x15, 0xcb, 0x99, 0xac, 0x2a, 0x29, 0x5a, 0xb2, 0xfc, 0xe5,
	0x41, 0x94, 0x15, 0xc7, 0xaf, 0x88, 0x3a, 0xc5, 0x53, 0x83, 0xb5, 0x21, 0x6b, 0x98, 0x74, 0xc6,
	0x9c, 0x17, 0xb1, 0xb7, 0xf0, 0x56, 0x93, 0xcd, 0xf3, 0x84, 0x2a, 0x9e, 0x6c, 0xfb, 0x86, 0x29,
	0xf4, 0xcd, 0x0b, 0xf2, 0x1a, 0xfc, 0x0a, 0xcd, 0x41, 0x16, 0xf1, 0xc3, 0xc2, 0x5b, 0x8d, 0xd3,
	0xeb, 0x8d, 0xc4, 0x30, 0x52, 0xf4, 0x52, 0x4a, 0x5a, 0xc4, 0x8f, 0xae, 0xd0, 0x5d, 0xc9, 0x5b,
	0x08, 0xd9, 0x81, 0x0a, 0x81, 0x65, 0x2e, 0x68, 0x85, 0xf1, 0xc0, 0x95, 0x27, 0x57, 0xf6, 0x85,
	0x56, 0x48, 0x5e, 0x81, 0x4f, 0x95, 0xb2, 0x13, 0x0c, 0x5d, 0x71, 0x48, 0x95, 0xda, 0x15, 0x84,
	0xc0, 0xa0, 0xe6, 0x7b, 0x11, 0xfb, 0x0e, 0xba, 0xb3, 0x65, 0xdf, 0x79, 0x89, 0xf1, 0x68, 0xe1,
	0xad, 0xc2, 0xd4, 0x9d, 0xc9, 0x1b, 0x18, 0x37, 0x35, 0xea, 0xdc, 0x89, 0x03, 0x27, 0x0e, 0x2c,
	0xc8, 0xf8, 0x5e, 0x2c, 0x7f, 0x7a, 0x10, 0x76, 0x59, 0x32, 0x85, 0xec, 0x3f, 0x32, 0xbf, 0x83,
	0xe8, 0x8f, 0x43, 0xa8, 0xc6, 0x5c, 0xb3, 0x4f, 0x7b, 0x8d, 0x85, 0x76, 0x0c, 0x3b, 0x4e, 0x9b,
	0xb2, 0x5d, 0x42, 0x60, 0x81, 0x8b, 0xf8, 0xa4, 0x5b, 0xd8, 0xfc, 0x78, 0xe8, 0x3f, 0x65, 0x86,
	0xfa, 0xcc, 0x19, 0x92, 0x0d, 0x84, 0x5c, 0x70, 0xd3, 0x45, 0x20, 0x2f, 0x6e, 0x12, 0xd9, 0xe4,
	0xf3, 0xa9, 0x43, 0xa9, 0x62, 0x29, 0xaa, 0xf2, 0xb2, 0x7c, 0x46, 0x3e, 0x42, 0x58, 0x1b, 0xa9,
	0x7a, 0xcf, 0x4b, 0x27, 0xb8, 0xfd, 0x47, 0xfe, 0x76, 0x7d, 0x82, 0x48, 0x63, 0x25, 0xcf, 0xf8,
	0x8f, 0xbe, 0x04, 0x7c, 0x2e, 0xce, 0xf2, 0x88, 0x77, 0xea, 0xdf, 0xc3, 0xf0, 0xd4, 0xa0, 0xbe,
	0xdc, 0x29, 0x5f, 0x43, 0xb0, 0x47, 0xb3, 0x45, 0x6d, 0xea, 0xfb, 0x1c, 0xdf, 0x7c, 0xf7, 0x2e,
	0x3e, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x7b, 0x66, 0xeb, 0x52, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SdkPeerServiceClient is the client API for SdkPeerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SdkPeerServiceClient interface {
	InitContract(ctx context.Context, in *ContractSpec, opts ...grpc.CallOption) (*RpcReply, error)
	StopContract(ctx context.Context, in *SdkPeerRequest, opts ...grpc.CallOption) (*RpcReply, error)
	RemoveContract(ctx context.Context, in *SdkPeerRequest, opts ...grpc.CallOption) (*RpcReply, error)
	Invoke(ctx context.Context, in *SdkPeerRequest, opts ...grpc.CallOption) (*RpcReply, error)
	Query(ctx context.Context, in *SdkPeerRequest, opts ...grpc.CallOption) (*RpcReply, error)
	GetCerts(ctx context.Context, in *SdkPeerRequest, opts ...grpc.CallOption) (*RpcReply, error)
}

type sdkPeerServiceClient struct {
	cc *grpc.ClientConn
}

func NewSdkPeerServiceClient(cc *grpc.ClientConn) SdkPeerServiceClient {
	return &sdkPeerServiceClient{cc}
}

func (c *sdkPeerServiceClient) InitContract(ctx context.Context, in *ContractSpec, opts ...grpc.CallOption) (*RpcReply, error) {
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, "/api.SdkPeerService/initContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkPeerServiceClient) StopContract(ctx context.Context, in *SdkPeerRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, "/api.SdkPeerService/stopContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkPeerServiceClient) RemoveContract(ctx context.Context, in *SdkPeerRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, "/api.SdkPeerService/removeContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkPeerServiceClient) Invoke(ctx context.Context, in *SdkPeerRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, "/api.SdkPeerService/invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkPeerServiceClient) Query(ctx context.Context, in *SdkPeerRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, "/api.SdkPeerService/query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkPeerServiceClient) GetCerts(ctx context.Context, in *SdkPeerRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, "/api.SdkPeerService/getCerts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SdkPeerServiceServer is the server API for SdkPeerService service.
type SdkPeerServiceServer interface {
	InitContract(context.Context, *ContractSpec) (*RpcReply, error)
	StopContract(context.Context, *SdkPeerRequest) (*RpcReply, error)
	RemoveContract(context.Context, *SdkPeerRequest) (*RpcReply, error)
	Invoke(context.Context, *SdkPeerRequest) (*RpcReply, error)
	Query(context.Context, *SdkPeerRequest) (*RpcReply, error)
	GetCerts(context.Context, *SdkPeerRequest) (*RpcReply, error)
}

// UnimplementedSdkPeerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSdkPeerServiceServer struct {
}

func (*UnimplementedSdkPeerServiceServer) InitContract(ctx context.Context, req *ContractSpec) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitContract not implemented")
}
func (*UnimplementedSdkPeerServiceServer) StopContract(ctx context.Context, req *SdkPeerRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopContract not implemented")
}
func (*UnimplementedSdkPeerServiceServer) RemoveContract(ctx context.Context, req *SdkPeerRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveContract not implemented")
}
func (*UnimplementedSdkPeerServiceServer) Invoke(ctx context.Context, req *SdkPeerRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (*UnimplementedSdkPeerServiceServer) Query(ctx context.Context, req *SdkPeerRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedSdkPeerServiceServer) GetCerts(ctx context.Context, req *SdkPeerRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCerts not implemented")
}

func RegisterSdkPeerServiceServer(s *grpc.Server, srv SdkPeerServiceServer) {
	s.RegisterService(&_SdkPeerService_serviceDesc, srv)
}

func _SdkPeerService_InitContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContractSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkPeerServiceServer).InitContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SdkPeerService/InitContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkPeerServiceServer).InitContract(ctx, req.(*ContractSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdkPeerService_StopContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SdkPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkPeerServiceServer).StopContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SdkPeerService/StopContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkPeerServiceServer).StopContract(ctx, req.(*SdkPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdkPeerService_RemoveContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SdkPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkPeerServiceServer).RemoveContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SdkPeerService/RemoveContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkPeerServiceServer).RemoveContract(ctx, req.(*SdkPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdkPeerService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SdkPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkPeerServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SdkPeerService/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkPeerServiceServer).Invoke(ctx, req.(*SdkPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdkPeerService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SdkPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkPeerServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SdkPeerService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkPeerServiceServer).Query(ctx, req.(*SdkPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdkPeerService_GetCerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SdkPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkPeerServiceServer).GetCerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SdkPeerService/GetCerts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkPeerServiceServer).GetCerts(ctx, req.(*SdkPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SdkPeerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.SdkPeerService",
	HandlerType: (*SdkPeerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "initContract",
			Handler:    _SdkPeerService_InitContract_Handler,
		},
		{
			MethodName: "stopContract",
			Handler:    _SdkPeerService_StopContract_Handler,
		},
		{
			MethodName: "removeContract",
			Handler:    _SdkPeerService_RemoveContract_Handler,
		},
		{
			MethodName: "invoke",
			Handler:    _SdkPeerService_Invoke_Handler,
		},
		{
			MethodName: "query",
			Handler:    _SdkPeerService_Query_Handler,
		},
		{
			MethodName: "getCerts",
			Handler:    _SdkPeerService_GetCerts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdk_peer.proto",
}
